### ISSUE TITLE
Why was removed from WP directory

### ISSUE THREAD

**Issue by nopticon** [fkrauthan/wp-mpdf#12]
Hello!

I was wondering if you have a reason of why was removed from WP plugin directory?
https://wordpress.org/plugins/wp-mpdf/

What kind of issue the plugin has?
Thank you!

**Comment by fkrauthan** [comment]
Interesting I didn't even notice that it was removed (Wordpress never send me as developer an email in regards of that). I'll look into this and try to get it reactivated.

**Comment by nopticon** [comment]
Thank you for your quick reply. I'm using the plugin for multiple project and willing the become a contributor to make some fixes.

**Comment by nopticon** [comment]
I saw that the plugin was reactivated in the directory, thank you. What do you think about my previous comment?

**Comment by fkrauthan** [comment]
Sorry I was going to answer you over the weekend but got busy. As you have already seen I've reached out to Wordpress to get the plugin reactivated.

I very much appreciate any contributions as I not longer use this plugin myself. I've seen your pull request and will look into that hopefully before Friday and release a new version to wp-mpdf.

**Comment by nopticon** [comment]
Perfect, thank you! If you need something, let me know.

**Comment by fkrauthan** [comment]
Ok new version is released
