### ISSUE TITLE
Getting the Post image 

### ISSUE THREAD

**Issue by Amm0o** [fkrauthan/wp-mpdf#14]
Good afternoon, 

I have been trying to get the post's thumbnail using the `the_post_thumbnail();`  function and using it in the deafult.php template.
I hasn't worked for me could you help me ? 

Thank you

**Comment by fkrauthan** [comment]
Can you please provide a bit more details what exactly is not working? And in general it is not recommended to edit the default templates. You should create a copy and configure that new template as your PDF template.

**Comment by fkrauthan** [comment]
Please proceed the questions in your support post https://wordpress.org/support/topic/getting-post-thumbnail-in-the-pdf/#post-13525081
