### ISSUE TITLE
Header & footer html problem

### ISSUE THREAD

**Issue by avantage-digital** [fkrauthan/wp-mpdf#15]
Hi in wp-mpdf.php line 226 :

`if ( $pdf_html_header ) {
    $mpdf->SetHTMLHeader( $pdf_header );
} else {
    $mpdf->setHeader( $pdf_header );
}
if ( $pdf_html_footer ) {
    $mpdf->SetHTMLFooter( $pdf_footer );
} else {
    $mpdf->setFooter( $pdf_footer );
}`

You use $pdf_header and $pdf_footer in the 2 states of the condition. So $pdf_html_header and $pdf_html_footer are never used.

Thanks for this plugin :)

Regards,

**Comment by fkrauthan** [comment]
I think when I added it the idea was that `$pdf_html_header` and `$pdf_html_footer` are Booleans that indicate if `$pdf_header` and `$pdf_footer` are ether raw HTML or mpdf's custom array format. Do you see any specific issue with this at the moment?

**Comment by avantage-digital** [comment]
Hi, I'm sorry I didn't understand :)
Yes it's very good like this !
Thanks a lot,
