### ISSUE TITLE
Your plugin was removed from the Wordpress Directory today

### ISSUE THREAD

**Issue by nixsee** [fkrauthan/wp-mpdf#18]
I just discovered your plugin but it was coincidentally removed from the WP Directory today. Any idea what is up and when it will be available again?

**Comment by fkrauthan** [comment]
Hey, yeah there is a small check I need to adjust then it will be back. Plan todo that together with the two pull requests that are open. So hopefully later this week.

**Comment by nixsee** [comment]
Great, thanks for the update!

**Comment by fkrauthan** [comment]
I've told the plugin should be available again. They had some issues with the way the cron job worked (they don't allow custom cron scripts anymore) and some validations they wanted me to add so I've complied with that.
