### ISSUE TITLE
PHP Warning (will be Error in next PHP version)

### ISSUE THREAD

**Issue by SeoDeveloper01** [fkrauthan/wp-mpdf#19]
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /domen/wp-content/plugins/wp-mpdf/mpdf/classes/ttfontsuni.php on line 613`

Pls fix

**Comment by SeoDeveloper01** [comment]
And here too
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /domen/wp-content/plugins/wp-mpdf/mpdf/classes/otl.php on line 5840`

**Comment by fkrauthan** [comment]
This will most likely go away with the MPDF v8 upgrade. See ticket #21 for status updates.
