### ISSUE TITLE
PHP Fatal error after update

### ISSUE THREAD

**Issue by SeoDeveloper01** [fkrauthan/wp-mpdf#22]
`PHP Fatal error:  Uncaught Error: Class 'Mpdf\Mpdf' not found in /domen/wp-content/plugins/wp-mpdf/wp-mpdf.php:195`

It looks like some files were not included in bundle after the update.
(PHP - 7.4, WP - 5.8.2, template - default)

**Comment by fkrauthan** [comment]
Oh no good catch. I forgot to add a folder as part of my deploy script. `3.7.1 should fix this (which should be released any minute now).

**Comment by mcyrulik** [comment]
It looks like 3.7.1 includes the vendor folder, but it looks like .gitignore file still excludes the the vendor folder. This is actually problematic for some of our sites that we manage. 

should line 14 of .gitignore be removed as well?

**Comment by fkrauthan** [comment]
What exactly do you mean with problematic? The folder is on purpose in `.gitignore` as I don't want the vendor folder in github. The release process installs the latest dependencies and then packages them for the wordpress plugin repo.

**Comment by mcyrulik** [comment]
Correct, it does package them into the release, and I can see why you would not want the vendor folder in the git repo. 

We have a .gitignore file in the main document root. On some sites, we have the plugins in our version control repository.

With the vendor folder in this plugin being ignored in your release/repo, our git repository sees your .gitignore and does not include the vendor folder in our repository.

**Comment by mcyrulik** [comment]
I can try those, thanks!

I understand completely not wanting the vendor folder in the git repo. That makes total sense. And it looks like you have updated your deploy script to specifically include that in a deployment - also makes sense. 

Just curious though, what would be the benefit of keeping the .gitignore file in the deployment at all? Is there a benefit to having that included when a website administrator downloads the plugin to their site? 

Thanks.

**Comment by fkrauthan** [comment]
I think it was more how I found other plugins doing it so I just copied it. Feel free to create a pull request to remove that file from future deployments.
