### ISSUE TITLE
Flex is not working for header

### ISSUE THREAD

**Issue by WassimAjouz** [fkrauthan/wp-mpdf#24]
I am currently working on a template for a pdf of a post on Wordpress and I am pretty sure that my css works ( I've built the html/css on a different file) but when implementing it on the header, the FLEX is not working any idea on how to solve it?

**Comment by fkrauthan** [comment]
I recommend checking the `mpdf` website to see what css is supported. That is the library that is used to convert HTML+CSS to a PDF.
