### ISSUE TITLE
how to hide

### ISSUE THREAD

**Issue by YeyeX64** [fkrauthan/wp-mpdf#30]
Hello, i try your plugin. It is the only standalone that i found.
I have a probleme, i have au bar on top on all page. I don't understand how hide pdf bar when i 'm not on White List page.

**Comment by fkrauthan** [comment]
Sorry can you be more specific what issue you have?

**Comment by YeyeX64** [comment]
sorry 
i have this bar on all page : 
![2023-11-14 11_42_38-Window](https://github.com/fkrauthan/wp-mpdf/assets/86892253/7e3ad5b8-d8eb-4912-adde-f2dccaa799c9)

but i want it only on selected page.

**Comment by fkrauthan** [comment]
If you disable the `Allow to Print all Pages` option in the MPDF Settings you can then whitelist specific pages. The button should only show up for whitelisted pages
