### ISSUE TITLE
Warning: Attempt to read property "login" on null

### ISSUE THREAD

**Issue by chicharitomagnetico** [fkrauthan/wp-mpdf#31]
Getting a Warning on line 356 of wp-mpdf/wp-mpdf.php
Attempt to read property "login" on null

`} else if ( ( get_option( 'mpdf_need_login' ) == 2 && $dsatz->login == false || get_option( 'mpdf_need_login' ) == 3 && $dsatz->login == true ) && is_user_logged_in() != true ) {`

**Comment by fkrauthan** [comment]
I added a default value which should prevent this warning from popping up in the upcoming release
