### ISSUE TITLE
custom fields and jquery chart

### ISSUE THREAD

**Issue by naeemnur** [fkrauthan/wp-mpdf#4]
Hello there,
I've created a custom post type with a bunch of custom fields and have used a jQuery gauge which i need to output in the pdf. 

Here is the frontend screenshot of the Cpt:
http://i.imgur.com/ACear68.png

and here is the pdf output:
http://i.imgur.com/gthyUuc.png

I want to make the pdf same as in frontend

**Comment by fkrauthan** [comment]
It is not possible to print out jquery generated content. The plugin can't execute Javascript.
