### ISSUE TITLE
format_to_post deprecated

### ISSUE THREAD

**Issue by NickGreen** [fkrauthan/wp-mpdf#6]
The file wp-mpdf.php uses a deprecated hook to sanitize the_content. Somewhere around line 264, it calls format_to_post('the_content');

FYI, format_to_post has been deprecated since WP 3.9, and hasn't been in use for a long time before that, so it wasn't really doing anything anyway.

My suggestion is to either get rid of that or replace it with wpdb::prepare()

**Comment by fkrauthan** [comment]
Removed the deprecated call. This is going with with the next release.
